spring.application.name=tijaro-marketplace-backend

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.datasource.url=jdbc:postgresql://localhost:5432/tijaro_marketplace
spring.datasource.username=postgres
spring.datasource.password=root123321

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=123456

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB

file.storage.upload-dir=uploads
file.storage.base-url=http://localhost:8080/uploads
